milk-shop-MVC/Controllers/CartController.cs
using AppService.IService;
using Microsoft.AspNetCore.Mvc;

namespace milk_shop_MVC.Controllers
{
    public class CartController : BaseController
    {
        public CartController(IProductService productService, IBrandService brandService, ICartDetailService cartDetailService, ICategoryService categoryService, IOrderService orderService, IOrderDetailService orderDetailService, IUserService userService) : base(productService, brandService, cartDetailService, categoryService, orderService, orderDetailService, userService)
        {
        }
        public async Task<IActionResult> Index()
        {
            int id = int.Parse(HttpContext.Session.GetString("userId"));
            if (id == 0)
            {
                throw new Exception("User not login");
            }
            var result = await _cartDetailService.GetCart(id);
            if (result is null)
            {
                ViewBag.Message = "Your Cart is empty";
            }
            return View(result);
        }
        public async Task<IActionResult> AddProductToCart(int Id, int qty)
        {
            var cart = new Cart
            {
                UserId = int.Parse(HttpContext.Session.GetString("userId")),
                IsBuyed = false,
                ProductId = Id,
                Quantity = qty
            };
            await _cartDetailService.CreateCartProduct(cart);
            return RedirectToAction("Index", "Product");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateQty(int id, int qty)
        {
            var cart = await _cartDetailService.GetCartById(id);
            cart.Quantity = qty;
            await _cartDetailService.UpdateCartProduct(cart);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var cart = await _cartDetailService.DeleteCartProduct(id);
            return RedirectToAction("Index");
        }
    }
}

milk-shop-MVC/Controllers/OrderController.cs
using AppService.IService;
using Microsoft.AspNetCore.Mvc;

namespace milk_shop_MVC.Controllers
{
    public class OrderController : BaseController
    {
        public OrderController(IProductService productService, IBrandService brandService, ICartDetailService cartDetailService, ICategoryService categoryService, IOrderService orderService, IOrderDetailService orderDetailService, IUserService userService) : base(productService, brandService, cartDetailService, categoryService, orderService, orderDetailService, userService)
        {
        }
        public async Task<IActionResult> Index()
        {
            int id = int.Parse(HttpContext.Session.GetString("userId"));
            if (id == 0)
            {
                throw new Exception("User not login");
            }
            var result = await _cartDetailService.GetCart(id);
            if (result is null)
            {
                ViewBag.Message = "Your Cart is empty";
            }
            return View(result);
        }
        [HttpPost]
        public async Task<IActionResult> CreateOrder(decimal total, List<KeyValuePair<int, int>> listQty)
        {
            var order = new Order
            {
                UserId = int.Parse(HttpContext.Session.GetString("userId")),
                OrderDate = DateTime.UtcNow,
                Total = total
            };
            await _orderService.CreateOrder(order);
            foreach (var item in listQty)
            {
                var orderProduct = new OrderProduct
                {
                    Order = order,
                    ProductId = item.Key,
                    Quantity = item.Value
                };
                await _orderDetailService.CreateOrderProduct(orderProduct);
            }
            var cart = await _cartDetailService.GetCart(int.Parse(HttpContext.Session.GetString("userId")));
            foreach (var item in cart)
            {
                item.IsBuyed = true;
                await _cartDetailService.UpdateCartProduct(item);
            }
            
            return RedirectToAction("Index", "Product");
        }


    }
}

milk-shop-MVC/Views/Cart/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    decimal total = 0;
}
@if (ViewBag.Message is not null)
{
    <script type="text/javascript">
        window.onload = function () {
            alert("@ViewBag.Message");
        };
    </script>
}
@model List<Cart>
<!--  Modal -->
<div class="modal fade" id="productView" tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content overflow-hidden border-0">
            <button class="btn-close p-4 position-absolute top-0 end-0 z-index-20 shadow-0" type="button" data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-body p-0">
                <div class="row align-items-stretch">
                    <div class="col-lg-6 p-lg-0"><a class="glightbox product-view d-block h-100 bg-cover bg-center" style="background: url(img/product-5.jpg)" href="img/product-5.jpg" data-gallery="gallery1" data-glightbox="Red digital smartwatch"></a><a class="glightbox d-none" href="img/product-5-alt-1.jpg" data-gallery="gallery1" data-glightbox="Red digital smartwatch"></a><a class="glightbox d-none" href="img/product-5-alt-2.jpg" data-gallery="gallery1" data-glightbox="Red digital smartwatch"></a></div>
                    <div class="col-lg-6">
                        <div class="p-4 my-md-4">
                            <ul class="list-inline mb-2">
                                <li class="list-inline-item m-0"><i class="fas fa-star small text-warning"></i></li>
                                <li class="list-inline-item m-0 1"><i class="fas fa-star small text-warning"></i></li>
                                <li class="list-inline-item m-0 2"><i class="fas fa-star small text-warning"></i></li>
                                <li class="list-inline-item m-0 3"><i class="fas fa-star small text-warning"></i></li>
                                <li class="list-inline-item m-0 4"><i class="fas fa-star small text-warning"></i></li>
                            </ul>
                            <h2 class="h4">Red digital smartwatch</h2>
                            <p class="text-muted">$250</p>
                            <p class="text-sm mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In ut ullamcorper leo, eget euismod orci. Cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus. Vestibulum ultricies aliquam convallis.</p>
                            <div class="row align-items-stretch mb-4 gx-0">
                                <div class="col-sm-7">
                                    <div class="border d-flex align-items-center justify-content-between py-1 px-3">
                                        <span class="small text-uppercase text-gray mr-4 no-select">Quantity</span>
                                        <div class="quantity">
                                            <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                                            <input class="form-control border-0 shadow-0 p-0" type="text" value="1">
                                            <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-sm-5"><a class="btn btn-dark btn-sm w-100 h-100 d-flex align-items-center justify-content-center px-0" href="cart.html">Add to cart</a></div>
                            </div><a class="btn btn-link text-dark text-decoration-none p-0" href="#!"><i class="far fa-heart me-2"></i>Add to wish list</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <!-- HERO SECTION-->
    <section class="py-5 bg-light">
        <div class="container">
            <div class="row px-4 px-lg-5 py-lg-4 align-items-center">
                <div class="col-lg-6">
                    <h1 class="h2 text-uppercase mb-0">Cart</h1>
                </div>
                <div class="col-lg-6 text-lg-end">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-lg-end mb-0 px-0 bg-light">
                            <li class="breadcrumb-item"><a class="text-dark" href="index.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Cart</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <section class="py-5">
        <h2 class="h5 text-uppercase mb-4">Shopping cart</h2>
        <div class="row">
            <div class="col-lg-8 mb-4 mb-lg-0">
                <!-- CART TABLE-->
                <div class="table-responsive mb-4">
                    <table class="table text-nowrap">
                        <thead class="bg-light">
                            <tr>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Product</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Price</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Quantity</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase">Total</strong></th>
                                <th class="border-0 p-3" scope="col"> <strong class="text-sm text-uppercase"></strong></th>
                            </tr>
                        </thead>
                        <tbody class="border-0">
                            <form method="post" asp-action="UpdateQty" asp-controller="Cart">
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <th class="ps-0 py-3 border-light" scope="row">
                                        <div class="d-flex align-items-center">
                                            <a class="reset-anchor d-block animsition-link" href="detail.html"><img src="@item.Product.ImageUrl" alt="..." width="70" /></a>
                                            <div class="ms-3"><strong class="h6"><a class="reset-anchor animsition-link" href="detail.html">@item.Product.ProductName</a></strong></div>
                                        </div>
                                    </th>
                                    <td class="p-3 align-middle border-light">
                                        <p class="mb-0 small">@item.Product.Price</p>
                                    </td>
                                    <td class="p-3 align-middle border-light">
                                        <div class="border d-flex align-items-center justify-content-between px-3">
                                            <span class="small text-uppercase text-gray headings-font-family">Quantity</span>
                                            <div class="quantity">
                                                <button class="dec-btn p-0"><i class="fas fa-caret-left"></i></button>
                                                <input class="form-control form-control-sm border-0 shadow-0 p-0" type="text" value="@item.Quantity" name="qty" />
                                                <input type="hidden" value="@item.Id" name="id"/>
                                                <button class="inc-btn p-0"><i class="fas fa-caret-right"></i></button>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="p-3 align-middle border-light">
                                        <p class="mb-0 small">
                                                @{
                                                    var price = item.Product.Price * item.Quantity;
                                                }
                                                @price VND
                                        </p>
                                    </td>
                                        @{
                                            total += item.Product.Price * item.Quantity;
                                        }
                                    <td class="p-3 align-middle border-light"><input class="reset-anchor" value="Edit" type="submit" /></td>
                                    <td class="p-3 align-middle border-light"><a class="reset-anchor" href="@Url.Action("Delete", "Cart", new{id = item.Id})"><i class="fas fa-trash-alt small text-muted"></i></a></td>

                                </tr>
                                }
                                </form>
                        </tbody>
                    </table>
                </div>
                <!-- CART NAV-->
                <div class="bg-light px-4 py-3">
                    <div class="row align-items-center text-center">
                        <div class="col-md-6 mb-3 mb-md-0 text-md-start"><a class="btn btn-link p-0 text-dark btn-sm" asp-action="Index" asp-controller="Product"><i class="fas fa-long-arrow-alt-left me-2"> </i>Continue shopping</a></div>
                        <div class="col-md-6 text-md-end"><a class="btn btn-outline-dark btn-sm" asp-action="Index" asp-controller="Order">Procceed to checkout<i class="fas fa-long-arrow-alt-right ms-2"></i></a></div>
                    </div>
                </div>
            </div>
            <!-- ORDER TOTAL-->
            <div class="col-lg-4">
                <div class="card border-0 rounded-0 p-lg-4 bg-light">
                    <div class="card-body">
                        <h5 class="text-uppercase mb-4">Cart total</h5>
                        <ul class="list-unstyled mb-0">
                            <li class="border-bottom my-2"></li>
                            <li class="d-flex align-items-center justify-content-between mb-4"><strong class="text-uppercase small font-weight-bold">Total</strong><span>@total VND</span></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>